### ISSUE TITLE
Help ? 

### ISSUE THREAD

**Issue by POSOFxBELA** [Daplie/pokemap-webapp#21]
Environment variables are successfully added.

Checking for existing RSA private key to secure login sessions...
RSA private key found, using it.
Listening on http://127.0.0.1:3000
Listening on https://localhost.daplie.com:3443
{ JsonWebTokenError: invalid signature
    at Object.module.exports [as verify] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\jsonwebtoken\verify.js:97:17)
    at attachSession (C:\Users\POSOFxBELA\Desktop\pokemap\index.js:323:22)
    at Layer.handle [as handle_request] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:271:10)
    at expressInit (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:312:13) name: 'JsonWebTokenError', message: 'invalid signature' }
{ JsonWebTokenError: invalid signature
    at Object.module.exports [as verify] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\jsonwebtoken\verify.js:97:17)
    at attachSession (C:\Users\POSOFxBELA\Desktop\pokemap\index.js:323:22)
    at Layer.handle [as handle_request] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:271:10)
    at expressInit (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:312:13) name: 'JsonWebTokenError', message: 'invalid signature' }
{ JsonWebTokenError: invalid signature
    at Object.module.exports [as verify] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\jsonwebtoken\verify.js:97:17)
    at attachSession (C:\Users\POSOFxBELA\Desktop\pokemap\index.js:323:22)
    at Layer.handle [as handle_request] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:271:10)
    at expressInit (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:312:13) name: 'JsonWebTokenError', message: 'invalid signature' }

What i need to do ?

**Comment by ikirt** [comment]
What version of node.js did you install ?

**Comment by POSOFxBELA** [comment]
6.3.1

**Comment by IceGroose** [comment]
Having the same problem, running Mac OS X with node 6.3.2

**Comment by coolaj86** [comment]
have you installed another version previously?

It sounds like you just need to log out and log back in.

**Comment by POSOFxBELA** [comment]
No i don't, but i didnt find the config.js in node-pokemon.. when you first time use it, you can see it on https://localhost.daplie.com:3443/
I did a search in the pokemon map for config.js and i paste my key there.. 

Is this the problem maybe?

**Comment by ikirt** [comment]
No you can still load up the site without the google API in the config, the page will inform you that the API is missing.
Have you tried uninstalling the node.js and reinstalling it ?
I primarily use linux, but did the window(fresh install) setup last night and it went without a hitch.

**Comment by POSOFxBELA** [comment]
Yes i did, i uninstalled node and removed the pokemon map, and i did everyting again but no result.

**Comment by ikirt** [comment]
Do you have the most recent version of the code ? 
Have you tried downloading the repo again ?

**Comment by POSOFxBELA** [comment]
Yes i tried everyting with no result :/

**Comment by ikirt** [comment]
To answer your other question about the config.js to edit, the path is the following:
pokemap\public\static\config.js
Try adding your google API key there and try again.

**Comment by POSOFxBELA** [comment]
Oke i followed these steps for putting in the api key, thank you

The cmd prop window giving me again the same text.. 

Environment variables are successfully added.



Checking for existing RSA private key to secure login sessions...
RSA private key found, using it.
Listening on http://127.0.0.1:3000
Listening on https://localhost.daplie.com:3443
{ JsonWebTokenError: invalid signature
    at Object.module.exports [as verify] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\jsonwebtoken\verify.js:97:17)
    at attachSession (C:\Users\POSOFxBELA\Desktop\pokemap\index.js:323:22)
    at Layer.handle [as handle_request] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:271:10)
    at expressInit (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\POSOFxBELA\Desktop\pokemap\node_modules\express\lib\router\index.js:312:13) name: 'JsonWebTokenError', message: 'invalid signature' }
{ JsonWebTokenError: invalid signature

**Comment by eknack** [comment]
Same issue for me, it happens after running the command and you open https://localhost.daplie.com:3443

**Comment by POSOFxBELA** [comment]
Yes, the same thing here, i logged out and logged in, the command windows is fixed i think but nothing on my https://localhost.daplie.com:3443/ screen.
