### ISSUE TITLE
TypeError: hex is not a function

### ISSUE THREAD

**Issue by infixman** [Daplie/pokemap-webapp#23]
## Current Behavior
Environment variables are successfully added.

Checking for existing RSA private key to secure login sessions...
Generating an RSA 1024-bit key to secure login sessions...
C:\Users\user\Downloads\pokemap-v1.3.8\pokemap\node_modules\rsa-compat\lib\rsa-extra.js:10
  var buf = Buffer.from(hex, 'hex');                   ^

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at _bigIntToBase64Url (C:\Users\user\Downloads\pokemap-v1.3.8\pokemap\node_modules\rsa-compat\lib\rsa-extra.js:10:20)
    at Object.module.exports._forgeToPrivateJwk (C:\Users\user\Downloads\pokemap-v1.3.8\pokemap\node_modules\rsa-compat\lib\rsa-extra.js:41:10)
    at Object.module.exports.exportPrivateJwk (C:\Users\user\Downloads\pokemap-v1.3.8\pokemap\node_modules\rsa-compat\lib\rsa-extra.js:105:21)
    at C:\Users\user\Downloads\pokemap-v1.3.8\pokemap\node_modules\rsa-compat\node.js:88:47
    at Object.module.exports.generateKeypair (C:\Users\user\Downloads\pokemap-v1.3.8\pokemap\node_modules\rsa-compat\lib\rsa-forge.js:66:5)
    at Object.RSA.generateKeypair (C:\Users\user\Downloads\pokemap-v1.3.8\pokemap\node_modules\rsa-compat\node.js:86:19)
    at ReadFileContext.callback (C:\Users\user\Downloads\pokemap-v1.3.8\pokemap\serve.js:57:7)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)

## Steps to Reproduce (for problems)
 1.download node node-v4.4.7-x64.msi & install with default option
 2.download pokemap-v1.3.8.zip & unzip
 3.dbl-click windows-pokemap.bat
 4.show the error msg
 5.close cmd window
 6.edit windows-pokemap.bat, change line 4
    [set NodePackagesPath="C:\Program Files\nodejs"]
    to
    [set NodePackagesPath="C:\Program Files (x86)\nodejs"]
    save & close
 7.dbl-click windows-pokemap.bat
 8.show the error msg again
 9.close cmd window
10.right click windows-pokemap.bat & run with admin
11.show the error msg again!!

## Your Computer
PC / Windows 10 / 64bit
C:\Users\user>node --version
v4.4.7

**Comment by Horgun** [comment]
You're supposed to use node-v6.3.1 or higher

**Comment by infixman** [comment]
@Horgun 
thx, i try use v6.3.1, it's rum!
i use my google api key,and login my ptc acc, it's no pokemon & no map..

![err](https://cloud.githubusercontent.com/assets/13029477/17522122/6a27720a-5e88-11e6-9c09-099f8b8fd6ca.png)

**Comment by Horgun** [comment]
Mine shows map but no pokemons or anything else =/. Trying to solve it
