### ISSUE TITLE
TokenExpiredError: jwt expired

### ISSUE THREAD

**Issue by Alaanor** [Daplie/pokemap-webapp#9]
First time that I try you're pokemap, I was able to enter my login credential and put the GMap API key.
I can see the location cursor move around my selected location, but there is no pokemon (really ?)
So, I take a look at the stacktrace:

```
[max@alaanor pokemap] ./linux-pokemap.bash
Checking for existing RSA private key to secure login sessions...
RSA private key found, using it.
Listening on http://127.0.0.1:3000
Listening on https://localhost.daplie.com:3443
{ TokenExpiredError: jwt expired
    at Object.module.exports [as verify] (/home/max/Downloads/pokemap-2/pokemap/node_modules/jsonwebtoken/verify.js:121:19)
    at attachSession (/home/max/Downloads/pokemap-2/pokemap/index.js:322:22)
    at Layer.handle [as handle_request] (/home/max/Downloads/pokemap-2/pokemap/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/max/Downloads/pokemap-2/pokemap/node_modules/express/lib/router/index.js:312:13)
    at /home/max/Downloads/pokemap-2/pokemap/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/max/Downloads/pokemap-2/pokemap/node_modules/express/lib/router/index.js:330:12)
    at next (/home/max/Downloads/pokemap-2/pokemap/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/max/Downloads/pokemap-2/pokemap/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/home/max/Downloads/pokemap-2/pokemap/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/max/Downloads/pokemap-2/pokemap/node_modules/express/lib/router/index.js:312:13)
  name: 'TokenExpiredError',
  message: 'jwt expired',
  expiredAt: 2016-08-01T20:06:35.000Z }
[max@alaanor pokemap]
```

## Expected Behavior
Displaying a error. (Maybe?)

## Current Behavior
Error in the stacktrace. (launch the pokemap from the console)

## Possible Solution
I don't know what does it mean. After this post, I'm going to do some search. But in any case I think this is a misconfiguration or a error, so, it's should ouput an error in the GUI.

## Steps to Reproduce (for bugs)
Hum ... After enter the GMap key. Just do ``./linux-pokemap.bash``

## Your Environment
* Version used: 1.3.4
* Environment name and version (e.g. Python 2.7):
Nodejs: v6.2.2
Python 3.5.1
* Operating System and version (desktop or mobile): Dekstop: 4.6.3-1-ARCH (Arch Linux)

## Note
Ho and, before I end this post, I didn't find the exact path for the config.js.
In my case it's on ``public/static/config.js`` in the ``gmaps_key`` variable. I wasn't able to find the exact directory, so maybe my error is here, otherwise, you should correct the path in the web page instruction.

**Comment by coolaj86** [comment]
Click logout and then login again. The token doesn't automatically renew yet.

**Comment by Alaanor** [comment]
Yeah, thank you. It's work now.

Sorry for the disagreement, I've opened a issue just for this >_<.

**Comment by coolaj86** [comment]
It's a valid issue. It needs to be fixed. :)

**Comment by coolaj86** [comment]
Moving conversion regarding this issue to here https://github.com/Daplie/node-pokemap/issues/18
